-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxr+Y4vyMfuMCuIUg
8ZNcrEFcGleh1cSIYRK3VhxYaOugCgYIKoZIzj0DAQehRANCAASiVytQ2kpdhl53
Gq/+CM/zQYtwP9i4TSyLfyqRT87oBIqiMPgFrBmB/7Kn3/tbpB1vluvsCKpdZ/rB
WJP40jfV
-----END PRIVATE KEY-----